import Head from "next/head";
import Link from "next/link";
import toast from "react-hot-toast";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link
          href={{
            pathname: "/[user]/userName",
            query: { user: "chenwi" },
          }}
        >
          <a>chenwi</a>
        </Link>

        <button onClick={() => {
          toast.success('Successfully toasted')
        }}>
          Toast
        </button>
      </main>
    </div>
  );
} toast
